---
title: "RPi Documentation"
author: "Ridhuan Syafiq"
format: gfm
editor: visual
---

## Objectives

-   Replicate spectrometer and weather station projects on RPi 5.

-   Check hardware/software for any depreciation/incompatibility with RPi5.

-   Repackage teaching materials.

-   Get as many RPi running.

## Key differences between RPi 5 vs RPi 3

-   Internet works fine with NUS_Guest. Need to use handphone for OTP, will give access for 5 days.

-   RPi 5 does not support installation of packages system-wide, necessitates the use of virtual environments. (discussed below)

-   

## Protocol for setting up new RPis

1.  Download [Raspberry Pi Imager](https://www.raspberrypi.com/software/).

2.  Plug in microsd card into a USB reader and follow set-up instructions on the imager app.

3.  Specifications

    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Setup steps                                | Choice                                                                                                                                                   |
    +============================================+==========================================================================================================================================================+
    | Device                                     | Raspberry Pi 5                                                                                                                                           |
    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
    | OS                                         | Raspberry Pi OS (64-bit). Released 2026-04-21.                                                                                                           |
    |                                            |                                                                                                                                                          |
    |                                            | 64 bit is important for RPi5 compatibility.\                                                                                                             |
    |                                            | Version is important for consistency. Might have to an additional step of downloading this particular image from archive if newer versions are released. |
    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Storage                                    | Select the USB reader                                                                                                                                    |
    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Hostname                                   | \*\*\*                                                                                                                                                   |
    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Localisation                               | Capital city \> Singapore (Singapore)\                                                                                                                   |
    |                                            | Timezone \> Asia/Singapore\                                                                                                                              |
    |                                            | Keyboard layout \> us                                                                                                                                    |
    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
    | User                                       | Username \> pi\                                                                                                                                          |
    |                                            | Password \> 12345                                                                                                                                        |
    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Wi-Fi                                      | **OPTIONAL\                                                                                                                                              |
    |                                            | **SSID \> NUS_Guest                                                                                                                                      |
    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Remote authentication/Raspberry Pi Connect | Default settings (not activated)                                                                                                                         |
    +--------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------+

4.  This will wipe the sd card and automatically format to FAT32.

5.  Plug-and-play into the RPi 5.

6.  Go to terminal to check date and time.

    Check: `timedatectl`\
    Change: `sudo date -s "25 MAY 2026 11:37:00"` (change accordingly).

## 

## Weather station

adafruit-dht is depreciated. need to update to [adafruit-circuitpython-dht](https://github.com/adafruit/Adafruit_CircuitPython_DHT)

## Adjusted code

pi_spectroscopy_v3-2.py, line 28 to 31

```{python}
#| eval: false

# OLD

def analogRead():                         #Read ADC value, only from Chn 0
    chan = AnalogIn(ads, ADS.P0)          #Reading from Chn 0
    current = (chan.value,chan.voltage)   #Extract Digital Value and Voltage
    return (current[0],current[1])
  
# NEW

def analogRead():                         
    chan = AnalogIn(ads, 0)               #Change this line (manually set int=0)
    current = (chan.value,chan.voltage)   
    return (current[0],current[1])
```

## Misc. Notes

python and python3 both refer to the same path. is there a difference?

maybe make the code more idiot-proof (low-priority)
